import os
from reportlab.lib.pagesizes import landscape, letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

OUTPUT_DIR = "gridsearch_output"
PDF_FILENAME = "grid_search_analysis_report.pdf"

def create_pdf(output_path, image_dir):
    c = canvas.Canvas(output_path, pagesize=landscape(letter))
    width, height = landscape(letter)
    
    # Title Page
    c.setFont("Helvetica-Bold", 30)
    c.drawCentredString(width / 2, height / 2 + 50, "Grid Search Analysis Report")
    c.setFont("Helvetica", 20)
    c.drawCentredString(width / 2, height / 2, "Comparison of Global EA vs Layer EA")
    c.drawCentredString(width / 2, height / 2 - 40, "Generated by NAS_LEGO")
    c.showPage()
    
    # Group images
    global_ea_images = []
    layer_ea_images = []
    
    for f in sorted(os.listdir(image_dir)):
        if not f.endswith(".png"):
            continue
        
        path = os.path.join(image_dir, f)
        if "global_ea" in f:
            global_ea_images.append(path)
        elif "layer_ea" in f:
            layer_ea_images.append(path)
    
    # Helper to draw image page
    def draw_image_page(img_path, title):
        try:
            img = ImageReader(img_path)
            img_w, img_h = img.getSize()
            aspect = img_h / float(img_w)
            
            # Fit to page with margins
            margin = 40
            avail_w = width - 2 * margin
            avail_h = height - 2 * margin - 50 # Reserve space for title
            
            if avail_w * aspect > avail_h:
                draw_h = avail_h
                draw_w = avail_h / aspect
            else:
                draw_w = avail_w
                draw_h = avail_w * aspect
            
            x = (width - draw_w) / 2
            y = (height - draw_h) / 2 - 20
            
            c.setFont("Helvetica-Bold", 18)
            c.drawCentredString(width / 2, height - 50, title)
            
            c.drawImage(img_path, x, y, width=draw_w, height=draw_h)
            c.showPage()
            print(f"Added page: {title}")
        except Exception as e:
            print(f"Failed to add image {img_path}: {e}")

    # Section 1: Global EA
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height / 2, "Section 1: Global Evolutionary Algorithm")
    c.showPage()
    
    for img_path in global_ea_images:
        filename = os.path.basename(img_path)
        # Extract n_blocks if possible
        title = filename
        if "nblk" in filename:
            try:
                # format: analysis_summary_nblkXX_global_ea.png
                parts = filename.split("_")
                for p in parts:
                    if p.startswith("nblk"):
                        nblk = p.replace("nblk", "")
                        title = f"Global EA - {nblk} Blocks"
                        break
            except:
                pass
        draw_image_page(img_path, title)
        
    # Section 2: Layer EA
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height / 2, "Section 2: Layer-wise Evolutionary Algorithm")
    c.showPage()
    
    for img_path in layer_ea_images:
        filename = os.path.basename(img_path)
        title = filename
        if "nblk" in filename:
            try:
                # format: analysis_summary_nblkXX_layer_ea.png
                parts = filename.split("_")
                for p in parts:
                    if p.startswith("nblk"):
                        nblk = p.replace("nblk", "")
                        title = f"Layer EA - {nblk} Blocks"
                        break
            except:
                pass
        draw_image_page(img_path, title)
        
    c.save()
    print(f"PDF Report saved to {output_path}")

if __name__ == "__main__":
    output_pdf = os.path.join(OUTPUT_DIR, PDF_FILENAME)
    create_pdf(output_pdf, OUTPUT_DIR)
